Repository Anushkabh/krishiconnect, pull requests merged in 2024-07, with the labels that each got.

#430 Change Logo of navbar and footer
  assets/css/stylesheet.css
  assets/img/logo/brand_logo/Dark_BG_logo.svg
  assets/img/logo/brand_logo/Light_BG_LOGO.svg
  assets/sass/_partials/_header.scss
  index.html
  src/about.html
  src/cart.html
  src/checkout.html
  src/contact.html
  src/detail-product.html
  src/faq.html
  src/feedback.html
  src/home.html
  src/login.html
  src/schemes.html
  src/setting.html
  src/shop.html
  src/success.html
  src/transaction.html
  src/wishlist.html
Labels: gssoc, level1

#666 Update style.css
  chatBot/style.css
Labels: gssoc, level1

#677 Update style.css
  assets/css/style.css
Labels: gssoc, level1

#705 Fix | issue #563
  assets/js/cart.js
Labels: gssoc, level1

#689 Feat:Footer Is Not Going With Ui #610
  assets/css/Footer-new.css
  backend/package-lock.json
  backend/package.json
  backend/server.js
  index.html
  src/about.html
  src/cart.html
  src/checkout.html
  src/contact.html
  src/detail-product.html
  src/faq.html
  src/feedback.html
  src/fruites.html
  src/home.html
  src/login.html
  src/miscellenous.html
  src/schemes.html
  src/setting.html
  src/shop.html
  src/success.html
  src/transaction.html
  src/vegetables.html
  src/wishlist.html
Labels: gssoc, level3

#710 fixed the chat bot
  chatBot/style.css
Labels: gssoc, level1

#716 Fixed : Dark mode in shop section
  src/shop.html
Labels: gssoc, level1

#720 Added Toastify Message
  assets/css/rateus.css
  src/rateus.html
Labels: gssoc, level1

#721 Added links to the footer and changed the logo in the footer on all pages
  assets/css/Footer-new.css
  index.html
  src/about.html
  src/cart.html
  src/checkout.html
  src/contact.html
  src/detail-product.html
  src/faq.html
  src/feedback.html
  src/fruites.html
  src/home.html
  src/login.html
  src/miscellenous.html
  src/schemes.html
  src/setting.html
  src/shop.html
  src/success.html
  src/transaction.html
  src/vegetables.html
  src/wishlist.html
Labels: gssoc, level1

#737 Made changes in the nav bar
  index.html
Labels: gssoc, level1

#740 Enhanced the FAQ Section
  src/faq.html
Labels: gssoc, level1

#730 Feat:want to add search bar in shop page #612
  assets/css/search.css
  assets/js/search.js
  src/rateus.html
  src/shop.html
Labels: gssoc, level2

#736 added thank you modal
  assets/js/cart.js
  src/cart.html
  src/contact.html
  src/login.html
  src/shop.html
  src/transaction.html
Labels: gssoc, level2

#741 fixed alignment
  assets/css/stylesheet.css
  assets/js/shop.js
  index.html
Labels: gssoc, level1

#745 Update server.js
  backend/server.js
Labels: gssoc, level1

#754 added blog page - fixes #635
  assets/css/Footer-new.css
  assets/css/blog.css
  assets/img/blog.jpg
  assets/js/blog.js
  assets/js/blogsData.js
  assets/js/test-script.js
  index.html
  src/about.html
  src/blog.html
  src/cart.html
  src/checkout.html
  src/contact.html
  src/detail-product.html
  src/faq.html
  src/feedback.html
  src/fruites.html
  src/home.html
  src/login.html
  src/miscellenous.html
  src/schemes.html
  src/setting.html
  src/shop.html
  src/transaction.html
  src/vegetables.html
  src/wishlist.html
Labels: gssoc, level3

#577 Oil seeds
  assets/css/oil-seeds.css
  src/oil-seeds.html
  src/shop.html
Labels: gssoc, level2

#766 Feat:Want to enhance Ui of NAvbar in mobile page #611
  assets/css/faq.css
  assets/css/stylesheet.css
  index.html
  src/about.html
  src/cart.html
  src/checkout.html
  src/contact.html
  src/detail-product.html
  src/faq.html
  src/feedback.html
  src/home.html
  src/login.html
  src/schemes.html
  src/setting.html
  src/shop.html
  src/success.html
  src/transaction.html
  src/wishlist.html
Labels: gssoc, level2

#762 favicon changed in home page
  index.html
Labels: good first issue, gssoc, level1

#758 add social icon on right of screen and added hovering effect
  assets/css/Footer-new.css
  index.html
  src/cart.html
  src/contact.html
  src/fruites.html
  src/shop.html
  src/transaction.html
  src/wishlist.html
Labels: gssoc, level2

#801 Corrected Footer on FAQ Page
  assets/css/faq.css
  src/faq.html
Labels: gssoc, level1

#806 appropriate SEO tags are added
  index.html
Labels: gssoc, level1

#782 enhanced the Rate Us page
  assets/css/rateus.css
  src/rateus.html
Labels: gssoc, level2

#824 Improvised Wishlist
  assets/js/shop.js
  assets/js/wishlist.js
  index.html
  src/shop.html
  src/wishlist.html
Labels: gssoc, level2

#693 payment checkout ui added
  assets/css/payment.css
  src/cart.html
  src/payment.html
Labels: gssoc, level2

#784 Added "Scroll Down Progress Bar" to the Website
  assets/css/index.css
  assets/css/style.css
  index.html
  src/about.html
  src/blog.html
  src/cart.html
  src/checkout.html
  src/common.html
  src/contact.html
  src/detail-product.html
  src/faq.html
  src/feedback.html
  src/fruites.html
  src/home.html
  src/login.html
  src/oil-seeds.html
  src/shop.html
  src/transaction.html
  src/vegetables.html
  src/wishlist.html
Labels: gssoc, level2
