Repository Anushkabh/krishiconnect, pull requests merged in 2024-06, with the labels that each got.

#451 Fixes Chatbot on Homepage
  chatBot/script.js
  chatBot/style.css
  index.html
  krishi.png
Labels: gssoc, level3

#452 navbar fixed for mobile screen
  cart(1).html
  contact(1).html
  home.html
  login.html
  shop(1).html
  transaction.html
Labels: gssoc, level2

#463 Update shop(1).html - Visibilty of text on Shopping Page
  shop(1).html
Labels: gssoc, level1

#471 Enhanced add to cart background
  assets/img/background_add_to_cart.webp
  cart(1).html
  cart.css
Labels: gssoc, level2

#477 Created register and login functionality.
  login.html
  stylesheet.css
Labels: gssoc, level2

#484 Bug fixes
  login.html
Labels: gssoc, level1

#490 Updated- Fruits and Vegetable page
  fruites.html
  vegetables.html
Labels: gssoc, level1

#418 Worked on Issue #359
  assets/css/theme.css
  index.css
  index.html
  stylesheet.css
  test-style.css
Labels: gssoc, level2

#435 Add Ratings
  shop(1).html
Labels: gssoc, level2

#443 Resolved Dark Mode Toggle Issue
  darkmode.js
Labels: gssoc, level2

#494 Miscellenous page
  Miscellenous.css
  Miscellenous.html
  shop(1).html
Labels: gssoc, level2

#503 fixed : wishlist page buttons get overlap on hover #464
  wishlist.html
Labels: gssoc, level1

#506 changed the look of faq page
  assets/img/llo.png
  assets/img/logo/faq.png
  faq(1).html
Labels: gssoc, level2

#514 Added Forgot Password
  login.html
Labels: gssoc, level2

#523 Refactor button elements to include text and vector inside the button tags
  cart(1).html
Labels: gssoc, level1

#540 Fixed BUTTONS in the cart
  cart(1).html
  cart.css
Labels: gssoc, level1

#539 contact.html file do in set and also give well structure
  contact(1).html
  stylesheet.css
Labels: gssoc, level2

#524 Made the Navbar of the FAQ page the same as the Navbar on other pages
  faq(1).html
  faq.css
Labels: gssoc, level1

#496 Major bugs fixed and overall improvement
  index.html
Labels: gssoc, level2

#537 Redesign shop
  cart(1).html
  index.html
  shop(1).html
Labels: gssoc, level2

#554 shop page fixed
  shop(1).html
  stylesheet.css
Labels: gssoc, level1

#556 toastify design secessfully
  shop(1).html
  shop.js
  toast.js
Labels: gssoc, level2

#560 Seller page is set !!!
  login.html
  stylesheet.css
Labels: gssoc, level1

#552 added bg for visibility
  transaction.html
  vegetables.html
  wishlist.html
Labels: gssoc, level1

#572 Corrected text and Added suitable image
  .DS_Store
  fresh-tomatoes.jpg-2.avif
  index.html
Labels: gssoc, level1

#573 Message added after submit contact form
  contact(1).html
Labels: gssoc, level1

#574 Added Rate Us Option
  index.html
  rateus.css
  rateus.html
Labels: gssoc, level2

#576 navigation same in whole website
  assets/css/theme.css
  assets/packages/o2system-ui/scss/o2system-ui/_utilities.scss
  cart(1).html
  login.html
  shop(1).html
  transaction.html
Labels: gssoc, level1

#650 Replaced Rp with ₹
  src/shop.html
Labels: gssoc, level1

#676 Update script.js
  assets/js/script.js
Labels: gssoc, level2

#665 Update script.js
  chatBot/script.js
Labels: gssoc, level2

#690 Issue #569 Solved, Added FAQ tab on the footer
  index.html
Labels: gssoc, level1

#692 ISSUE #615 Updated Shop
  src/shop.html
Labels: gssoc, level1
