Repository Anushkabh/krishiconnect, pull requests merged in 2024-05, with the labels that each got.

#47 Files structured
  Css-Files/stylehome.css
  Css-Files/stylesheet.css
  Html-Files/about(1).html
  Html-Files/cart(1).html
  Html-Files/checkout(1).html
  Html-Files/contact(1).html
  Html-Files/faq(1).html
  Html-Files/home.html
  Html-Files/login.html
  Html-Files/schemes.html
  Html-Files/setting(1).html
  Html-Files/shop(1).html
  Html-Files/success.html
  Html-Files/transaction.html
  Images/GOVERNMENT SCHEMES W.jpg
  Images/Kisan-credit-card-A-Government-of-India-scheme-to-save-farmers.jpg
  Images/R (1).jpg
  Images/R.jpg
  Images/file.jpg
  Images/images-12-min.jpeg
  Images/krishiconnect-high-resolution-logo-color-on-transparent-background (1).png
  Images/sc1.jpg
  Images/sc2.jpg
  Images/sc3.png
  Images/sc4.jpg
  Images/sc5.jpg
  Images/sc6.jpg
  Images/sc7.jpg
  Images/sunlight-forest-children-water-nature-grass-114691-wallhere.com.jpg
  Js-Files/cart.js
  Js-Files/checkout.js
  Js-Files/homescript.js
  Js-Files/script.js
  Js-Files/script1.js
  Js-Files/shop.js
  Js-Files/transaction.js
  index.html
Labels: gssoc, level1

#32 feat: added issue btns and respective forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: gssoc, level1

#57 added navigation button to quickly move to the top
  .vscode/settings.json
  assets/css/theme.css
  assets/js/theme.js
  index.html
  shop(1).html
Labels: gssoc, level1

#59 Improved the cart page
  cart(1).html
  stylesheet.css
Labels: level2

#60 Redesigned the README.md file
  README.md
Labels: gssoc, level1

#69 add | decrease quantity button in cart UI
  cart.js
Labels: gssoc, level1

#34 modified: assets/css/theme.css
  assets/css/theme.css
  stylesheet.css
Labels: gssoc, level1

#87 Hover Effect On Buttons Issue #37
  assets/css/theme.css
Labels: gssoc, level2

#98 README.md file are added with pictures and other related things
  1.png
  2.png
  3.png
  4.png
  5.png
  6.png
  README.md
  assets/ss/1.png
  assets/ss/2.png
  assets/ss/3.png
  assets/ss/4.png
  assets/ss/5.png
  assets/ss/6.png
Labels: gssoc, level1

#73 fix FAQ section by reordering questions #8
  faq(1).html
Labels: gssoc, level1

#101 Fix logo in FAQ section
  faq(1).html
Labels: gssoc, level1

#107 [REPOST] make all the cards of same size
  shop(1).html
Labels: gssoc, level2

#112 social link working
  index.html
Labels: gssoc, level1

#109 feat: automate greetings using github bot
  .github/workflows/greetings.yml
Labels: gssoc, level2

#93 fix:Add hover to cards
  shop(1).html
Labels: gssoc, level2

#105 Fixed Footer issue #15
  about(1).html
  assets/css/theme.css
  cart(1).html
  checkout(1).html
  contact(1).html
  faq(1).html
  home.html
  index.html
  login.html
  schemes.html
  setting(1).html
  shop(1).html
  success.html
  transaction.html
Labels: gssoc, level1

#115 fixed typos
  assets/css/theme.css
  index.html
  script.js
  shop(1).html
Labels: gssoc, level1

#116 changed logo
  about(1).html
  assets/img/farmer.png
  assets/img/logo/log.png
  assets/img/logo/new.png
  assets/img/logo/nn.png
  assets/img/shop.png
  assets/img/wht.png
  cart(1).html
  faq(1).html
  home.html
  index.html
  schemes.html
  shop(1).html
  stylehome.css
  transaction.html
Labels: gssoc, level3

#122 Updated background images relevant to the website UI
  .gitignore
  assets/img/bg.jpg
  assets/img/cart.jpg
  cart(1).html
Labels: gssoc, level1

#123 loader added
  index.css
  index.html
  index.js
Labels: gssoc, level2

#124 Favicon added
  about(1).html
  cart(1).html
  checkout(1).html
  contact(1).html
  faq(1).html
  home.html
  index.html
  login.html
  schemes.html
  setting(1).html
  shop(1).html
  success.html
  transaction.html
Labels: gssoc, level1

#127 shop now section is improved #89
  assets/css/theme.css
  index.html
Labels: gssoc, level2

#128 improvement in cart section
  cart(1).html
  stylesheet.css
Labels: gssoc, level2

#140 Done corrections in faq(1).html
  faq(1).html
Labels: gssoc, level1

#133 Fix | cart item update in local storage
  cart.js
Labels: gssoc, level2

#132 adding social media icons to footer
  index.html
  stylesheet.css
Labels: gssoc, level1

#146 Added Website Title to KrishiConnect Pages
  about(1).html
  cart(1).html
  contact(1).html
  faq(1).html
  home.html
  login.html
  schemes.html
  setting(1).html
  shop(1).html
  success.html
  transaction.html
  wishlist.html
Labels: gssoc, level1

#134 Fixed | Cart total display on visiting cart
  cart.js
  stylesheet.css
Labels: gssoc, level3

#136 navbar elements added
  about(1).html
  cart(1).html
  contact(1).html
  faq(1).html
  index.html
  package-lock.json
  shop(1).html
  transaction.html
Labels: gssoc, level2

#151 Fixed issue #129
  index.html
Labels: gssoc, level1

#171 fixed navitems to be aligned and added home page to wishlist
  wishlist.html
Labels: gssoc, level2

#158 Added icons on navbar
  cart(1).html
  shop(1).html
  transaction.html
Labels: gssoc, level2

#161 Feat: Reveal items on scroll!!
  about(1).html
  cart(1).html
  checkout(1).html
  faq(1).html
  index.html
  login.html
  schemes.html
  setting(1).html
  shop(1).html
  success.html
  transaction.html
  wishlist.html
Labels: gssoc, level3

#177 add to cart button alert added wrt issue #157
  shop(1).html
Labels: gssoc, level2

#180 foot category logo update wrt issue #156
  assets/img/logo/apple.png
  assets/img/logo/carrot.png
  assets/img/logo/flax-seed.png
  assets/img/logo/nutrition.png
  assets/img/logo/seed.png
  assets/img/logo/tea.png
  shop(1).html
Labels: gssoc, level2

#182 Krishiconnect logo alignment done issue #155
  about(1).html
  cart(1).html
  contact(1).html
  faq(1).html
  index.css
  index.html
  login.html
  shop(1).html
  transaction.html
Labels: gssoc, level2

#172 Fixed streched logo
  shop(1).html
Labels: gssoc, level1

#183 Make navbar visible and solve index page black issue and solved logo alignment issue
  about(1).html
  cart(1).html
  checkout(1).html
  contact(1).html
  faq(1).html
  home.html
  index.css
  index.html
  login.html
  schemes.html
  setting(1).html
  shop(1).html
  stylehome.css
  success.html
  transaction.html
  wishlist.html
Labels: gssoc, level3

#189 Updated the Login/Sign up page
  login.html
  stylesheet.css
Labels: gssoc, level3

#207 FOOTER UPGRADED
  assets/css/theme.css
  cart(1).html
  stylesheet.css
Labels: gssoc, level3

#186 added and improve the contact us page
  assets/css/theme.css
  assets/sass/_partials/_color.scss
  assets/sass/_partials/_global.scss
  contact(1).html
  d142d8b7a2e493ab8e6523ec42a5c420.jpg
  index.css
  index.html
  stylehome.css
  stylesheet.css
Labels: gssoc, level3

#218 Update Issue #176
  about(1).html
  cart(1).html
  shop(1).html
  transaction.html
  wishlist.html
Labels: gssoc, level2

#221 fixed-issue-#143
  shop(1).html
Labels: gssoc, level3

#231 added product detail page [#56]
  assets/img/review.jpg
  detail-product(1).html
  detail-product(2).html
  shop(1).html
  style.css
Labels: gssoc, level3

#232 Enhancement: Improved hero section of shop page.
  shop(1).html
Labels: gssoc, level3

#239 Fixed contact us page #117
  contact(1).html
  index.html
Labels: gssoc, level2

#245 [BUG] : Cart page Quantiy fixed
  cart.js
Labels: gssoc, level2

#248 Successfully Created Section "what our clients say"
  assets/img/review_icon.png
  assets/img/reviews.png
  assets/img/reviews1.png
  index.css
  index.html
Labels: gssoc, level3

#249 Added icons
  shop(1).html
  transaction.html
  wishlist.html
Labels: gssoc, level2

#269 Favicon added
  cart(1).html
Labels: gssoc, level1

#266 Worked on hovering effect of the page
  index.css
Labels: gssoc, level2

#194 Feat: Reveal items on scroll!!
  about(1).html
  cart(1).html
  checkout(1).html
  contact(1).html
  faq(1).html
  home.html
  login.html
  schemes.html
  setting(1).html
  shop(1).html
  success.html
  transaction.html
  wishlist.html
Labels: gssoc, level3

#283 Improved the UI of enter the details section in the carts
  bright-blending-colors.jpg
  cart(1).html
  cart.css
Labels: gssoc, level3

#289 Text visible now!
  index.css
Labels: gssoc, level2

#263 Fix | Cart item responsiveness issue#135
  .vscode/settings.json
  cart(1).html
  cart.js
  stylesheet.css
Labels: gssoc, level2

#310 Fix:Navbar-hero
  login.html
Labels: gssoc, level2

#309 Updated Added Hovering to cards in Shop categories
  shop(1).html
Labels: gssoc, level2

#329 Fix: Made text appear in both light and dark modes.
  darkmode.css
Labels: gssoc, level2

#330 Update the Contact section
  assets/css/theme.css
  contact(1).html
Labels: gssoc, level2

#311 redesign footer
  cart(1).html
  checkout(1).html
  index.html
  sharmi.html
  shop(1).html
  success.html
  transaction.html
  wishlist.html
Labels: gssoc, level2

#333 changeDocumentation
  index.html
Labels: gssoc, level1

#335 Updated FAQ Page
  faq(1).html
Labels: gssoc, level3

#336 Add to Cart is now at center
  shop(1).html
Labels: gssoc, level1

#337 Vegetables, Fruits, Oils seeds etc are now redirecting to their correct sections
  shop(1).html
Labels: gssoc, level1

#339 [BUG] : Dark & Light mode doesn't proper fixed
  darkmode.css
Labels: gssoc, level2

#343 Created:Feat:Add to Cart Ui Enhanchment #307
  assets/img/green-back.webp
  cart(1).html
  cart.css
  cart.js
  shop(1).html
  shop.js
  stylesheet.css
Labels: gssoc, level3

#346 img card completely done with hover effect
  index.css
  index.html
Labels: gssoc, level1

#350 Commit- New tomato image(product section)
  assets/img/tomato2.jpg
Labels: gssoc, level1

#347 Add dynamic copyright year to footer
  about(1).html
  cart(1).html
  checkout(1).html
  contact(1).html
  detail-product(1).html
  detail-product(2).html
  faq(1).html
  feedback.html
  home.html
  index.html
  login.html
  schemes.html
  setting(1).html
  sharmi.html
  shop(1).html
  success.html
  transaction.html
  wishlist.html
Labels: gssoc, level2

#352 Corrected the alignment on navbar of login page
  login.html
  stylesheet.css
Labels: gssoc, level2

#185 Fixes Issue #184
  home.html
  stylehome.css
Labels: gssoc
